name: Build and Deploy Github Pages Files

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Git Status
      run: git status
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Create Birthday Meals File
      run: |
        python loadBirthMealToArray.py


    - name: Test Conditional
      run: |
        if [[ `git status --porcelain` ]]; then echo "yes"; else echo "no"; fi
    
    - name: Git Globals
      run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" \
           git config --global user.name "$GITHUB_ACTOR"

    - name: Commit birthday menu changes
      run: |
        if [[ `git status --porcelain` ]]; then  git add . && git commit -m"Auto update birthday menu" && echo "changes committed"; else echo "no changes to commit"; fi

