name: Build and Deploy Github Pages Files

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Git Status
      run: git status
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Create Birthday Meals File
      run: |
        python loadBirthMealToArray.py
    
    - name: many way to get variable print config
      env:
        ACTOR: ${{ github.actor }}
      run: echo "$GITHUB_ACTOR""@users.noreply.github.com
          ${GITHUB_ACTOR}@users.noreply.github.com
          $GITHUB_ACTOR
          $ACTOR
          ${ACTOR}@users.noreply.github.com
          ${{ github.actor }}"

    - name: Git Globals
      env:
        ACTOR: ${{ github.actor }}
        AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com

      run: git config --global user.email $AUTHOR_EMAIL \
           git config --global user.name $ACTOR

    - name: Commit birthday menu changes
      env:
        ACTOR: ${{ github.actor }}
        AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
      run: |
        git config --global user.email $AUTHOR_EMAIL \
        git config --global user.name $ACTOR \
        if [[ `git status --porcelain` ]]; then  git add . && git commit -m"Auto update birthday menu" && echo "changes committed"; else echo "no changes to commit"; fi

